In [2]:
import pandas as pd
from pandas import DataFrame

# Series和Series连接
s1 = pd.Series(["A", "B"], index=[1, 2])
s2 = pd.Series(["D", "E"], index=[4, 5])
s3 = pd.Series(["G", "H"], index=[7, 8])

pd.concat([s1, s2, s3])
pd.concat([s1, s2, s3],axis=1)

     0    1    2
1    A  NaN  NaN
2    B  NaN  NaN
4  NaN    D  NaN
5  NaN    E  NaN
7  NaN  NaN    G
8  NaN  NaN    H

In [4]:
# DataFrame和Series连接
df1 = pd.DataFrame(data={"a": [1, 2], "b": [4, 5]}, index=[1, 2])
s1 = pd.Series(data=[7, 10], index=[1, 2], name="a")

s1

pd.concat([df1,s1])
pd.concat([df1,s1],axis=1)

   a  b   a
1  1  4   7
2  2  5  10

In [6]:
# DataFrame与DataFrame连接
df1 = pd.DataFrame(data={"a": [1, 2], "b": [4, 5]}, index=[1, 2])
df2 = pd.DataFrame(data={"a": [7, 8], "b": [10, 11]}, index=[1, 2])

df2
pd.concat([df1,df2])
pd.concat([df1,df2],axis=1)

   a  b  a   b
1  1  4  7  10
2  2  5  8  11

In [7]:
df1 = pd.DataFrame(data={"a": [1, 2], "b": [4, 5]}, index=[1, 2])
df2 = pd.DataFrame(data={"a": [7, 8], "b": [10, 11]}, index=[1, 2])

df2
# 通过ignore_index=True重置索引
pd.concat([df1,df2],ignore_index=True)

   a   b
0  1   4
1  2   5
2  7  10
3  8  11

In [32]:
# 通过concat实现类似join的效果
df1 = pd.DataFrame(data={"a": [1, 2], "b": [4, 5]}, index=[1, 2])
df2 = pd.DataFrame(data={"b": [7, 8], "c": [10, 11]}, index=[2, 3])

df2
# 默认实现的是类似全外连接的效果
pd.concat([df1,df2],join="outer")

pd.concat([df1,df2],join="inner",axis=1)
# pd.concat([df1,df2],join="left",axis=1)

# 总结：concat一般就是在对结果集进行合并的时候使用

   a  b  b   c
2  2  5  7  10