In [5]:
from doctest import DocFileCase

# 一对一
import pandas as pd
df1 = pd.DataFrame(
    {"employee": ["Bob", "Jake", "Lisa", "Sue"], "group": ["Accounting", "Engineering", "Engineering", "HR"]}
)
df2 = pd.DataFrame({"employee": ["Lisa", "Bob", "Jake", "Sue"], "hire_date": [2004, 2008, 2012, 2014]})

df2

# 默认用两个df中同名字段进行连接
pd.merge(df1, df2)
df1.merge(df2)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [9]:
# 多对一
df1 = pd.DataFrame(
    {"employee": ["Bob", "Jake", "Lisa", "Sue"], "group": ["Accounting", "Engineering", "Engineering", "HR"]}
)
df2 = pd.DataFrame({"group": ["Accounting", "Engineering", "HR"], "supervisor": ["Carly", "Guido", "Steve"]})


pd.merge(df1, df2)

  employee        group supervisor
0      Bob   Accounting      Carly
1     Jake  Engineering      Guido
2     Lisa  Engineering      Guido
3      Sue           HR      Steve

In [14]:
# 多对多
df1 = pd.DataFrame(
    {"employee": ["Bob", "Jake", "Lisa", "Sue"], "group": ["Accounting", "Engineering", "Engineering", "HR"]}
)
df2 = pd.DataFrame(
    {
        "group": ["Accounting", "Accounting", "Engineering", "Engineering", "HR", "HR"],
        "skills": ["math", "spreadsheets", "coding", "linux", "spreadsheets", "organization"],
    }
)

pd.merge(df1, df2)

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [19]:
# （1）通过on指定使用某个列连接，只能在有共同列名的时候使用
df1 = pd.DataFrame(
    {"employee": ["Bob", "Jake", "Lisa", "Sue"], "group": ["Accounting", "Engineering", "Engineering", "HR"]}
)
df2 = pd.DataFrame({"employee": ["Lisa", "Bob", "Jake", "Sue"], "hire_date": [2004, 2008, 2012, 2014]})

pd.merge(df1, df2,on="employee")

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [24]:
# （2）两对象列名不同，通过left_on和right_on分别指定列名
df1 = pd.DataFrame(
    {"employee": ["Bob", "Jake", "Lisa", "Sue"], "group": ["Accounting", "Engineering", "Engineering", "HR"]}
)
df2 = pd.DataFrame({"name": ["Bob", "Jake", "Lisa", "Sue"], "salary": [70000, 80000, 120000, 90000]})

pd.merge(df1, df2,left_on="employee", right_on="name")

  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [39]:
# （3）通过left_index和right_index设置合并的索引
# 通过设置merge()中的left_index、right_index参数将索引设置为键来实现合并

df1 = pd.DataFrame(
    {"employee": ["Bob", "Jake", "Lisa", "Sue"], "group": ["Accounting", "Engineering", "Engineering", "HR"]}
)
df2 = pd.DataFrame({"name": ["Lisa", "Bob", "Jake", "Sue"], "hire_date": [2004, 2008, 2012, 2014]})


# pd.merge(df1,df2)
# pd.merge(df1,df2,on="employee")
# pd.merge(df1,df2,left_on="employee", right_on="employee")

df1.set_index("employee", inplace=True)
df2.set_index("name", inplace=True)

pd.merge(df1, df2,left_index=True, right_index=True)

# df2

            group  hire_date
Bob    Accounting       2008
Jake  Engineering       2012
Lisa  Engineering       2004
Sue            HR       2014

In [52]:
# DataFrame实现了join()方法，可以按照索引进行数据合并。但要求没有重叠的列，或通过lsuffix、rsuffix指定重叠列的后缀。

df1 = pd.DataFrame({
    'key': ['A', 'B', 'C'],
    'value1': [1, 2, 3]
})

df2 = pd.DataFrame({
    'key': ['B', 'C', 'D'],
    'value2': [4, 5, 6]
})
# df2.set_index('key', inplace=True)

# pd.merge(df1, df2)
# pd.merge(df1, df2,left_index=True, right_index=True)

# df1.join(df2,lsuffix='_join',rsuffix='_left')
# df1.join(df2,on='key')

In [68]:
df1 = pd.DataFrame({"name": ["Peter", "Paul", "Mary"], "food": ["fish", "beans", "bread"]}, columns=["name", "food"])
df2 = pd.DataFrame({"name": ["Mary", "Joseph"], "drink": ["wine", "beer"]}, columns=["name", "drink"])

df2

# 默认使用的是内连接   只会将完全匹配的数据关联上
pd.merge(df1, df2)

# 可以通过how参数指定连接类型
# 默认how='inner'
pd.merge(df1, df2,how="inner")

# 全外连接
pd.merge(df1, df2, how="outer")

# concat只是对结果集进行合并，如果要实现全外连接效果，还是需要通过merge，指定how='outer'
# pd.concat([df1, df2])

# 左外连接
pd.merge(df1, df2, how="left")

# 右外连接
pd.merge(df1, df2, how="right")
#
# pd.merge(df1, df2, how="outer", on="name")

     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

In [66]:
# 4）重复列名的处理
df1 = pd.DataFrame({"name": ["Bob", "Jake", "Lisa", "Sue"], "rank": [1, 2, 3, 4]})
df2 = pd.DataFrame({"name": ["Bob", "Jake", "Lisa", "Sue"], "rank": [3, 1, 4, 2]})

 # 不指定后缀名，默认为_x和_y
# pd.merge(df1, df2,on="name")
pd.merge(df1, df2,on="name",suffixes=("_left", "_right"))

   name  rank_left  rank_right
0   Bob          1           3
1  Jake          2           1
2  Lisa          3           4
3   Sue          4           2