In [ ]:

import numpy as np
import pandas as pd


# Python的内置类型，表示没有返回  或者没有初始化的情况   NoneType
type(None)

# 表述的是数值的特殊值   不是一个数   float
type(np.nan)

# 表述的数据的可用以及不可用性   pandas._libs.missing.NAType
type(pd.NA)

s = pd.Series([np.nan, None, pd.NA])
s.isnull()
s.isna()

s.notnull()
s.notna()

In [ ]:
# 加载带缺失值的文件
df = pd.read_csv("E:\\250716_大模型\\05_尚硅谷大模型技术之Numpy&Pandas\\2.资料\\data\\weather_withna.csv")

# 如果导入的数据有空数据  默认用缺失值进行填充
df.tail()

# 如果不想用缺失值进行填充  就保留空值   通过keep_default_na参数设置是否将空白值设置为缺失值
df = pd.read_csv("E:\\250716_大模型\\05_尚硅谷大模型技术之Numpy&Pandas\\2.资料\\data\\weather_withna.csv",keep_default_na=False)
df.tail()

# 可通过na_values参数将指定值设置为缺失值。
df = pd.read_csv("E:\\250716_大模型\\05_尚硅谷大模型技术之Numpy&Pandas\\2.资料\\data\\weather_withna.csv",na_values="2015-12-31")
df.tail()

# 查看缺失值的数量      df.isna()=>返回一个df，里面的数据都是布尔类型，  True=1  False=0   ，所以可以通过sum()计算缺失值
df.isna().sum()

In [ ]:
import missingno as msno
df = pd.read_csv("E:\\250716_大模型\\05_尚硅谷大模型技术之Numpy&Pandas\\2.资料\\data\\weather_withna.csv")

msno.bar(df)
msno.heatmap(df)

In [27]:
# 1）Series剔除缺失值
s = pd.Series([1, pd.NA, None])
s.dropna()

0    1
dtype: object

In [35]:
# 2）DataFrame剔除缺失值
# 无法从DataFrame中单独剔除一个值，只能剔除缺失值所在的整行或整列。
df = pd.DataFrame([[1, pd.NA, 2], [2, 3, 5], [pd.NA, 4, 6]])
df
# 默认情况下，dropna()会剔除任何包含缺失值的整行数据。
df.dropna()
# axis=1 会剔除任何包含缺失值的整列数据。
df.dropna(axis=1,how='all')

      0     1  2
0     1  <NA>  2
1     2     3  5
2  <NA>     4  6

In [43]:
df = pd.DataFrame([[1, pd.NA, 2], [pd.NA, pd.NA, 5], [pd.NA, pd.NA, pd.NA]])
# df.dropna(how='all',axis=1)

# thresh=n   至少有n个值不是缺失值 当前行|列数据才会保留
df.dropna(thresh=2)

   0     1  2
0  1  <NA>  2

In [49]:
# 可以通过设置subset参数来设置某一列有缺失值则进行剔除。
df = pd.DataFrame([[1, pd.NA, 2], [pd.NA, pd.NA, 5], [pd.NA, pd.NA, pd.NA]])
df
df.dropna(subset=[1])

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [56]:
# 填充缺失值
# 1）使用固定值填充
# 通过fillna()方法，传入值或字典进行填充。
df = pd.read_csv("E:\\250716_大模型\\05_尚硅谷大模型技术之Numpy&Pandas\\2.资料\\data\\weather_withna.csv")
df.fillna(0, inplace=True)
df.tail()

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0       0.0       0.0   0.0       0
1457  2015-12-28            0.0       0.0       0.0   0.0       0
1458  2015-12-29            0.0       0.0       0.0   0.0       0
1459  2015-12-30            0.0       0.0       0.0   0.0       0
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [59]:
# 使用字典来填充
df = pd.read_csv("E:\\250716_大模型\\05_尚硅谷大模型技术之Numpy&Pandas\\2.资料\\data\\weather_withna.csv")
df.fillna({"temp_max":60,"temp_min":-60}, inplace=True)
df.tail()

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      60.0     -60.0   NaN     NaN
1457  2015-12-28            NaN      60.0     -60.0   NaN     NaN
1458  2015-12-29            NaN      60.0     -60.0   NaN     NaN
1459  2015-12-30            NaN      60.0     -60.0   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [72]:
# 通过fillna()方法，传入统计后的值进行填充。
df = pd.read_csv("E:\\250716_大模型\\05_尚硅谷大模型技术之Numpy&Pandas\\2.资料\\data\\weather_withna.csv")
df.fillna(df[["precipitation","temp_max","temp_min","wind"]].mean(), inplace=True)
df.tail()

            date  precipitation   temp_max  temp_min      wind weather
1456  2015-12-27       3.052332  15.851468  7.877202  3.242055     NaN
1457  2015-12-28       3.052332  15.851468  7.877202  3.242055     NaN
1458  2015-12-29       3.052332  15.851468  7.877202  3.242055     NaN
1459  2015-12-30       3.052332  15.851468  7.877202  3.242055     NaN
1460  2015-12-31      20.600000  12.200000  5.000000  3.800000    rain

In [76]:
# 通过ffill()或bfill()方法使用前面或后面的有效值填充。
df = pd.read_csv("E:\\250716_大模型\\05_尚硅谷大模型技术之Numpy&Pandas\\2.资料\\data\\weather_withna.csv")
# df.ffill(inplace=True)
df.bfill(inplace=True)
df.tail()

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [78]:
s = pd.Series([1, np.nan, 3, 4, np.nan, 6])
s.interpolate()

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64